const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const dataset = JSON.parse(fs.readFileSync(path.join(root, 'data/contacts.json'), 'utf8'));
const checks = [];
function check(value, label) { if (!value) throw new Error(label); checks.push(label); }
async function main() {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, headless: true, args: ['--no-sandbox'] });
  const context = await browser.newContext({ viewport: { width: 1500, height: 1050 }, acceptDownloads: true });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  try {
    const server = process.env.TEST_SERVER || 'http://127.0.0.1:8790';
    await page.goto(server); await page.waitForSelector('tbody tr');
    check(await page.locator('tbody tr').count() === 25, 'Live React/FastAPI page loads with 25 rows');
    check((await page.locator('tbody tr').first().innerText()).includes('AI + 真机线索'), 'Default sort prioritizes AI with physical robot evidence');
    await page.screenshot({ path: path.join(root, 'preview-desktop.png') });
    await page.locator('.view-tabs button').filter({ hasText: '本次新增' }).click();
    check((await page.locator('.pagination').innerText()).includes('/ 100 位'), 'Added batch has exactly 100 candidates');
    await page.getByRole('button', { name: '重置筛选', exact: true }).click();
    await page.getByRole('combobox', { name: '学校', exact: true }).selectOption('MIT');
    await page.getByRole('combobox', { name: 'AI与真机匹配', exact: true }).selectOption('ai-real');
    const expected = dataset.contacts.filter(r => r.school === 'MIT' && r.fitCategory === 'ai-real');
    check(await page.locator('tbody tr').count() === expected.length, 'School and AI/physical filter compose');
    check((await page.locator('.pagination').innerText()).includes(`/ ${expected.length} 位`), 'Filtered count matches the actual intersection');
    const popupEvent = context.waitForEvent('page');
    await page.locator('.sidebar').getByRole('link', { name: '新标签页打开研究方向' }).click();
    const popup = await popupEvent; await popup.waitForSelector('.direction-card');
    check(await popup.getByRole('combobox', { name: '学校', exact: true }).inputValue() === 'MIT', 'New direction tab preserves selected school');
    check(await popup.getByRole('combobox', { name: 'AI与真机匹配', exact: true }).inputValue() === 'ai-real', 'New direction tab preserves AI filter');
    await popup.getByRole('combobox', { name: '细分研究方向' }).selectOption('强化学习 / 泛化');
    const areaExpected = expected.filter(r => r.researchAreas.includes('强化学习 / 泛化'));
    check(await popup.locator('tbody tr').count() === areaExpected.length, 'Direction page intersects school, AI and granular research area');
    check(popup.url().includes('school=MIT') && popup.url().includes('area='), 'Selected filters are encoded in a shareable URL');
    await popup.reload(); await popup.waitForSelector('tbody tr');
    check(await popup.locator('tbody tr').count() === areaExpected.length, 'Direct direction URL survives reload');
    const card = popup.locator('.direction-card').filter({ hasText: '强化学习 / 泛化' });
    check((await card.locator('strong').innerText()).startsWith(String(areaExpected.length)), 'Direction card count uses the same filtered pool');
    const downloadEvent = popup.waitForEvent('download');
    await popup.getByRole('button', { name: /导出名单/ }).click();
    const download = await downloadEvent; const target = path.join('/tmp', 'summer-research-expansion-test.csv'); await download.saveAs(target);
    const csv = fs.readFileSync(target, 'utf8');
    check(csv.includes('AI与真机匹配') && csv.includes('研究来源') && areaExpected.every(r => csv.includes(r.name)), 'Filtered export contains evidence and every matching record');
    check(!csv.includes('Sergey Levine'), 'School filter also constrains export');
    await popup.getByRole('button', { name: '重置筛选', exact: true }).click();
    await popup.waitForFunction(() => !document.querySelector('.toast.visible'));
    await popup.screenshot({ path: path.join(root, 'preview-directions.png') });
    await popup.close();
    await page.getByRole('button', { name: '重置筛选', exact: true }).click();
    await page.locator('.identity-filters summary').click();
    await page.getByRole('combobox', { name: '本人公开族裔与性别' }).selectOption('white_male');
    check(await page.locator('tbody tr').count() === 0, 'Unsourced white/male identities are not guessed');
    check((await page.locator('.empty').innerText()).includes('本人自述'), 'Identity empty state explains the missing sourced data');
    await page.getByRole('combobox', { name: '本人公开族裔与性别' }).selectOption('unknown');
    check((await page.locator('.pagination').innerText()).includes('/ 200 位'), 'Unknown identities remain browseable');
    await page.getByRole('button', { name: '重置筛选', exact: true }).click();
    await page.evaluate(() => localStorage.setItem('summer-research-2027-progress-v1', JSON.stringify({ 'Siddharth Karamcheti': { saved:true, status:'已联系', personalNote:'旧版联系记录验证' } })));
    await page.reload(); await page.waitForSelector('tbody tr');
    await page.getByRole('textbox', { name: '搜索导师、学校、方向', exact: true }).fill('旧版联系记录验证');
    check(await page.locator('tbody tr').count() === 1 && (await page.locator('tbody tr').innerText()).includes('Siddharth Karamcheti'), 'Original 100-person notes stay mapped to the same faculty member');
    check(await page.locator('tbody select').inputValue() === '已联系', 'Original contact status survives the expansion');
    await page.getByRole('button', { name: '重置筛选', exact: true }).click();
    await page.setViewportSize({ width:390, height:844 }); await page.screenshot({ path:path.join(root,'preview-mobile.png') });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile list has no page-level horizontal overflow');
    await page.getByRole('button', { name:'打开导航', exact:true }).click();
    await page.locator('#mobile-nav').getByRole('button', { name:'方向总览', exact:true }).click();
    check(await page.locator('dialog#mobile-nav[open]').count() === 0, 'Mobile direction navigation closes the drawer');
    check(await page.locator('.direction-card').count() === dataset.meta.researchAreas.length, 'Mobile direction browser shows all granular research categories');
    await page.screenshot({path:path.join(root,'preview-directions-mobile.png')});
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile direction cards fit the viewport');
    const api = await (await page.request.get(server+'/api/browse?school=MIT&fit=ai-real')).json();
    check(api.total === expected.length && api.contacts.every(r => r.school==='MIT'), 'Browse API and frontend filter counts agree');
    const directions = await (await page.request.get(server+'/api/directions?school=MIT&fit=ai-real')).json();
    check(directions.find(r => r.area==='强化学习 / 泛化').total === areaExpected.length, 'Direction API and frontend card counts agree');
    const exported = await (await page.request.get(server+'/api/contacts/export?school=MIT&fit=ai-real')).text();
    check(expected.every(r => exported.includes(r.name)) && !exported.includes('Sergey Levine'), 'Backend export applies school and AI filters');
    const invalid = await page.request.get(server+'/api/browse?identity=guess'); check(invalid.status()===422,'API rejects unsupported identity filters');
    await page.goto('file://'+path.join(root,'index.html')+'#directions?school=MIT&fit=ai-real'); await page.waitForSelector('.direction-card');
    check(await page.locator('tbody tr').count()===expected.length,'Standalone HTML supports direct direction URLs with school filters');
    check(errors.length===0,'No browser script errors');
    fs.writeFileSync(path.join(root,'expansion-verification.json'),JSON.stringify({checkedAt:'2026-10-01',checks,browserErrors:errors},null,2));
    console.log(JSON.stringify({checks,browserErrors:errors}));
  } finally { await browser.close(); }
}
main().catch(error => { console.error(error); process.exit(1); });
