const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const path = require('node:path');
const fs = require('node:fs');
const root = path.resolve(__dirname, '..');
const dataset = JSON.parse(fs.readFileSync(path.join(root, 'data/contacts.json'), 'utf8'));
const [first, second] = [...dataset.contacts].sort((a, b) => ['ai-real','ai-pending','robotics'].indexOf(a.fitCategory) - ['ai-real','ai-pending','robotics'].indexOf(b.fitCategory) || a.id-b.id);
const checks = [];
const check = (value, label) => { if (!value) throw new Error(label); checks.push(label); };
async function eventually(read, label) {
  for (let i = 0; i < 50; i++) { if (await read()) { checks.push(label); return; } await new Promise(resolve => setTimeout(resolve, 100)); }
  throw new Error(label);
}
const seed = () => {
  window.__microphoneTracks = []; window.__failAudioWrites = false; window.__failTextWrites = false;
  const getMedia = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
  navigator.mediaDevices.getUserMedia = async constraints => {
    const stream = await getMedia(constraints); window.__microphoneTracks.push(...stream.getTracks()); return stream;
  };
  const transaction = IDBDatabase.prototype.transaction;
  IDBDatabase.prototype.transaction = function (names, mode, ...args) {
    const tx = transaction.call(this, names, mode, ...args);
    if (window.__failAudioWrites && mode === 'readwrite' && Array.from(typeof names === 'string' ? [names] : names).includes('audio')) queueMicrotask(() => tx.abort());
    return tx;
  };
  const setItem = Storage.prototype.setItem;
  Storage.prototype.setItem = function (key, value) {
    if (window.__failTextWrites && key === 'summer-research-2027-progress-v1') throw new DOMException('test storage full', 'QuotaExceededError');
    return setItem.call(this, key, value);
  };
};
async function main() {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, headless: true,
    args: ['--no-sandbox', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
  const browserErrors = []; const networkRequests = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1500, height: 1000 }, acceptDownloads: true });
    await context.addInitScript(seed);
    const page = await context.newPage(); page.on('pageerror', e => browserErrors.push(e.message));
    page.on('request', request => networkRequests.push(request.url()));
    const dialog = page.locator('.notes-dialog[open]');
    await page.goto('file://' + path.join(root, 'index.html')); await page.waitForSelector('tbody tr');
    check(await page.getByRole('button', { name: /^录音 / }).count() === 25 && await page.getByRole('button', { name: /^备注 / }).count() === 25, 'every visible contact has recording and text buttons');
    await page.getByRole('button', { name: `备注 ${first.name}`, exact: true }).click();
    await dialog.getByLabel('文字备注', { exact: true }).fill('方向很匹配，想看机器人学习论文。\n邮件里问八周访问，优先读机器人论文。');
    await dialog.getByRole('button', { name: '收藏，稍后联系', exact: true }).click();
    await dialog.getByLabel('联系进度', { exact: true }).selectOption('暂不联系');
    await dialog.getByRole('button', { name: '完成', exact: true }).click();
    await page.reload(); await page.waitForSelector('tbody tr');
    await page.getByRole('button', { name: `备注 ${first.name}`, exact: true }).click();
    check((await dialog.getByLabel('文字备注', { exact: true }).inputValue()).includes('优先读机器人论文'), 'multiline personal note survives reload');
    check(await dialog.getByLabel('联系进度', { exact: true }).inputValue() === '暂不联系', 'note editor preserves existing contact progress');
    check(await dialog.getByRole('button', { name: '已收藏 · 点击取消', exact: true }).count() === 1, 'note editor preserves favorites');
    await dialog.getByRole('button', { name: '完成', exact: true }).click();
    await page.getByRole('textbox', { name: '搜索导师、学校、方向', exact: true }).fill('优先读机器人论文');
    await eventually(async () => await page.locator('tbody tr').count() === 1, 'personal notes are searchable');
    await page.getByRole('button', { name: '重置筛选', exact: true }).click();
    await page.getByRole('button', { name: `录音 ${first.name}`, exact: true }).click();
    await dialog.getByRole('button', { name: '停止并保存', exact: true }).waitFor();
    await page.waitForTimeout(1200);
    await dialog.getByRole('button', { name: '停止并保存', exact: true }).click();
    await dialog.locator('.saved-recordings audio').waitFor();
    await eventually(() => page.evaluate(() => window.__microphoneTracks.length > 0 && window.__microphoneTracks.every(track => track.readyState === 'ended')), 'stopping releases the microphone');
    check(await dialog.locator('.saved-recordings audio').count() === 1, 'real MediaRecorder capture saves one clip');
    await dialog.locator('audio').evaluate(audio => audio.play());
    await eventually(() => dialog.locator('audio').evaluate(audio => audio.currentTime > 0), 'saved recording plays back');
    const audioDownload = page.waitForEvent('download'); await dialog.getByRole('link', { name: '下载录音', exact: true }).click();
    const audio = await audioDownload; const audioPath = path.join('/tmp', 'summer-research-notes-test.webm'); await audio.saveAs(audioPath);
    check(fs.statSync(audioPath).size > 100, 'download contains actual audio bytes');
    await page.screenshot({ path: path.join(root, 'preview-notes-desktop.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(root, 'preview-notes-mobile.png') });
    check(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), 'notes editor fits mobile without horizontal overflow');
    await page.setViewportSize({ width: 1500, height: 1000 });
    await dialog.getByRole('button', { name: '完成', exact: true }).click();
    await page.reload(); await page.waitForSelector('tbody tr');
    await page.getByRole('combobox', { name: '备注筛选', exact: true }).selectOption('audio');
    await eventually(async () => await page.locator('tbody tr').count() === 1, 'audio filter works after reload');
    await page.getByRole('button', { name: `备注 ${first.name}`, exact: true }).click();
    await dialog.locator('.saved-recordings audio').waitFor();
    await dialog.locator('audio').evaluate(audio => audio.play());
    await eventually(() => dialog.locator('audio').evaluate(audio => audio.currentTime > 0), 'audio blob survives reload and remains playable');
    await dialog.getByRole('button', { name: '开始录音', exact: true }).click();
    await dialog.getByRole('button', { name: '停止并保存', exact: true }).waitFor(); await page.waitForTimeout(350);
    await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' });
    await page.getByRole('button', { name: `备注 ${first.name}`, exact: true }).click();
    await eventually(async () => await dialog.locator('.saved-recordings audio').count() === 2, 'Escape stops and saves active recording before closing');
    await dialog.getByRole('button', { name: '完成', exact: true }).click();
    const exportDownload = page.waitForEvent('download'); await page.getByRole('button', { name: /导出名单/ }).click();
    const csv = await exportDownload; const csvPath = path.join('/tmp', 'summer-research-notes-test.csv'); await csv.saveAs(csvPath);
    const contents = fs.readFileSync(csvPath, 'utf8');
    check(contents.includes('"我的看法"') && contents.includes('优先读机器人论文') && contents.includes('"录音数量"') && contents.includes('"2"') && contents.includes('.webm'), 'CSV contains multiline notes, recording count and filenames');
    await page.getByRole('button', { name: '重置筛选', exact: true }).click();
    await page.getByRole('button', { name: `录音 ${second.name}`, exact: true }).click();
    await dialog.getByRole('button', { name: '停止并保存', exact: true }).waitFor(); await page.waitForTimeout(350);
    await page.evaluate(() => { window.__failAudioWrites = true; });
    await dialog.getByRole('button', { name: '停止并保存', exact: true }).click();
    await dialog.getByRole('button', { name: '重试保存录音', exact: true }).waitFor();
    check(await dialog.locator('.pending-recording audio').count() === 1 && await dialog.locator('.saved-recordings audio').count() === 0, 'failed audio storage preserves downloadable recording without claiming success');
    await page.evaluate(() => { window.__failAudioWrites = false; });
    await dialog.getByRole('button', { name: '重试保存录音', exact: true }).click();
    await dialog.locator('.saved-recordings audio').waitFor();
    check(await dialog.locator('.pending-recording').count() === 0, 'failed recording can be saved by retry');
    check(await dialog.getByLabel('文字备注', { exact: true }).inputValue() === '', 'notes stay associated with the correct contact');
    await page.evaluate(() => { window.__failTextWrites = true; });
    await dialog.getByLabel('文字备注', { exact: true }).fill('temporary note');
    check(await dialog.getByRole('status').filter({ hasText: '未能保存' }).count() === 1, 'text storage failure is visible');
    await page.evaluate(() => { window.__failTextWrites = false; });
    await dialog.getByLabel('文字备注', { exact: true }).fill('saved after retry');
    check(await dialog.getByRole('status').filter({ hasText: '自动保存到此浏览器' }).count() === 1, 'editing again recovers from text storage failure');
    await dialog.getByRole('button', { name: '删除', exact: true }).click();
    await dialog.getByRole('button', { name: '确认删除', exact: true }).click();
    await eventually(async () => await dialog.locator('.saved-recordings audio').count() === 0, 'recording deletion updates the current contact');
    await dialog.getByRole('button', { name: '完成', exact: true }).click();
    await page.reload(); await page.waitForSelector('tbody tr');
    await page.getByRole('button', { name: `备注 ${second.name}`, exact: true }).click();
    check(await dialog.locator('.saved-recordings audio').count() === 0 && await dialog.getByLabel('文字备注', { exact: true }).inputValue() === 'saved after retry', 'deletion persists while text remains');
    await dialog.getByRole('button', { name: '完成', exact: true }).click();
    check(networkRequests.every(url => url.startsWith('file:') || url.startsWith('blob:') || url.startsWith('data:')), 'offline notes make no network or Qwen requests');
    const denied = await browser.newContext();
    await denied.addInitScript(() => { navigator.mediaDevices.getUserMedia = async () => { throw new DOMException('test permission denial', 'NotAllowedError'); }; });
    const deniedPage = await denied.newPage(); deniedPage.on('pageerror', e => browserErrors.push(e.message));
    await deniedPage.goto('file://' + path.join(root, 'index.html')); await deniedPage.waitForSelector('tbody tr');
    await deniedPage.getByRole('button', { name: `录音 ${first.name}`, exact: true }).click();
    await deniedPage.getByRole('alert').filter({ hasText: '麦克风权限未开启' }).waitFor();
    await deniedPage.getByLabel('文字备注', { exact: true }).fill('permission denied but text works');
    await deniedPage.locator('.notes-dialog').getByRole('button', { name: '完成', exact: true }).click();
    await deniedPage.reload(); await deniedPage.waitForSelector('tbody tr');
    await deniedPage.getByRole('button', { name: `备注 ${first.name}`, exact: true }).click();
    check(await deniedPage.getByLabel('文字备注', { exact: true }).inputValue() === 'permission denied but text works', 'permission denial gives actionable message and text still saves');
    await denied.close();
    await page.goto(process.env.TEST_SERVER || 'http://127.0.0.1:8790'); await page.waitForSelector('tbody tr');
    await page.getByRole('button', { name: `备注 ${first.name}`, exact: true }).click();
    check(await dialog.getByLabel('文字备注', { exact: true }).inputValue() === '', 'file and HTTP storage are independent');
    await dialog.getByLabel('文字备注', { exact: true }).fill('HTTP local app note');
    await dialog.getByRole('button', { name: '开始录音', exact: true }).click(); await dialog.getByRole('button', { name: '停止并保存', exact: true }).waitFor();
    await page.waitForTimeout(350); await dialog.getByRole('button', { name: '停止并关闭', exact: true }).click();
    await dialog.waitFor({ state: 'detached' }); await page.reload(); await page.waitForSelector('tbody tr');
    await page.getByRole('button', { name: `备注 ${first.name}`, exact: true }).click(); await dialog.locator('.saved-recordings audio').waitFor();
    check(await dialog.getByLabel('文字备注', { exact: true }).inputValue() === 'HTTP local app note', 'FastAPI served app persists audio and text after stop-and-close');
    await dialog.getByRole('button', { name: '完成', exact: true }).click();
    await page.getByRole('button', { name: '详情', exact: true }).first().click();
    await page.locator('.detail-dialog[open]').getByRole('button', { name: '记录我的看法', exact: true }).click();
    await dialog.waitFor(); check(await dialog.getByRole('heading', { name: first.name, exact: true }).count() === 1, 'faculty details open the correct notes editor');
    check(browserErrors.length === 0, 'no browser script errors');
    const result = { checkedAt: new Date().toISOString(), audioInput: 'Chromium fake microphone with real MediaRecorder encoding', checks, browserErrors };
    fs.writeFileSync(path.join(root, 'notes-verification.json'), JSON.stringify(result, null, 2));
    console.log(JSON.stringify(result)); fs.unlinkSync(audioPath); fs.unlinkSync(csvPath);
  } finally { await browser.close(); }
}
main().catch(e => { console.error(e); process.exit(1); });
